language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install tox-travis
script:
  - tox
  - tox -e checkstyle
  - tox -e testcov
  - tox -e lint
  - tox -e checktypes
  - tox -e documentation
env:
  OMP_NUM_THREADS: 4
